-- V001__create_schema.sql
-- CyberSafe LA Option B schema from the approved Entity Relationship Diagram and data dictionary.
-- No extra tables, fields, relationships, or cardinalities are added here.
-- Primary keys use bigint with PostgreSQL identity generation as specified in the data dictionary.

CREATE TABLE IF NOT EXISTS business (
  business_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  naics VARCHAR(10) NOT NULL,
  employee_count INT NOT NULL CHECK (employee_count >= 0),
  address TEXT,
  ccpa_flag BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(business_id),
  name TEXT NOT NULL,
  role VARCHAR(100),
  email TEXT NOT NULL,
  phone VARCHAR(30),
  outreach_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cohort (
  cohort_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term VARCHAR(50) NOT NULL,
  academic_year VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultant (
  consultant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cohort_id BIGINT NOT NULL REFERENCES cohort(cohort_id),
  competency_level VARCHAR(50) NOT NULL,
  specialization TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT consultant_competency_level_check
    CHECK (competency_level IN ('Foundation', 'Professional', 'Expert'))
);

CREATE TABLE IF NOT EXISTS faculty_advisor (
  faculty_advisor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department TEXT NOT NULL,
  expertise_area TEXT,
  advising_capacity INT CHECK (advising_capacity IS NULL OR advising_capacity >= 0),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS industry_mentor (
  mentor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expertise_area TEXT NOT NULL,
  assigned_client_cohort TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mou (
  mou_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(business_id),
  pdf_url TEXT NOT NULL,
  version VARCHAR(50) NOT NULL,
  signature_date DATE NOT NULL,
  scope_statement TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS partner (
  partner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  partner_type VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS referral (
  referral_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id BIGINT NOT NULL REFERENCES partner(partner_id),
  business_id BIGINT NOT NULL REFERENCES business(business_id),
  referral_date DATE,
  conversion_outcome VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engagement (
  engagement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(business_id),
  faculty_advisor_id BIGINT NOT NULL REFERENCES faculty_advisor(faculty_advisor_id),
  mou_id BIGINT NOT NULL REFERENCES mou(mou_id),
  status VARCHAR(50) NOT NULL,
  opened_date DATE NOT NULL,
  closed_date DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT engagement_status_check
    CHECK (status IN ('Intake', 'MOU Execution', 'Assessment', 'Reporting', 'Follow-Up', 'Closed', 'Cancelled')),
  CONSTRAINT engagement_closed_date_check
    CHECK (closed_date IS NULL OR closed_date >= opened_date)
);

CREATE TABLE IF NOT EXISTS assignment (
  assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engagement_id BIGINT NOT NULL REFERENCES engagement(engagement_id),
  consultant_id BIGINT NOT NULL REFERENCES consultant(consultant_id),
  mentor_id BIGINT REFERENCES industry_mentor(mentor_id),
  role VARCHAR(100),
  hours_commitment INT CHECK (hours_commitment IS NULL OR hours_commitment >= 0),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questionnaire_response (
  response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(business_id),
  engagement_id BIGINT NOT NULL REFERENCES engagement(engagement_id),
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  score_summary TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_base_entry (
  knowledge_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engagement_id BIGINT NOT NULL REFERENCES engagement(engagement_id),
  domain TEXT NOT NULL,
  finding_title TEXT NOT NULL,
  finding_description TEXT NOT NULL,
  severity VARCHAR(50) NOT NULL,
  recommended_remediat TEXT NOT NULL,
  dbir_reference TEXT NOT NULL,
  framework_reference TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT knowledge_base_domain_check
    CHECK (domain IN (
      'Account and Identity',
      'Endpoint and Updates',
      'Network and Wi-Fi',
      'Data Protection and Backups',
      'Third-Party and Vendor Risk',
      'Awareness and Response'
    )),
  CONSTRAINT knowledge_base_severity_check
    CHECK (severity IN ('Critical', 'High', 'Medium', 'Low', 'Informational'))
);

CREATE TABLE IF NOT EXISTS audit_log_entry (
  audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_role TEXT NOT NULL,
  entity_name TEXT NOT NULL,
  action_type TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT audit_log_action_type_check
    CHECK (action_type IN ('SELECT', 'INSERT', 'UPDATE', 'SOFT_DELETE', 'RESTORE', 'EXPORT', 'LOGIN', 'PERMISSION_TEST'))
);

CREATE INDEX IF NOT EXISTS idx_contact_business_id ON contact(business_id);
CREATE INDEX IF NOT EXISTS idx_consultant_cohort_id ON consultant(cohort_id);
CREATE INDEX IF NOT EXISTS idx_assignment_engagement_id ON assignment(engagement_id);
CREATE INDEX IF NOT EXISTS idx_assignment_consultant_id ON assignment(consultant_id);
CREATE INDEX IF NOT EXISTS idx_assignment_mentor_id ON assignment(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mou_business_id ON mou(business_id);
CREATE INDEX IF NOT EXISTS idx_referral_partner_id ON referral(partner_id);
CREATE INDEX IF NOT EXISTS idx_referral_business_id ON referral(business_id);
CREATE INDEX IF NOT EXISTS idx_engagement_business_id ON engagement(business_id);
CREATE INDEX IF NOT EXISTS idx_engagement_faculty_advisor_id ON engagement(faculty_advisor_id);
CREATE INDEX IF NOT EXISTS idx_engagement_mou_id ON engagement(mou_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_response_business_id ON questionnaire_response(business_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_response_engagement_id ON questionnaire_response(engagement_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_entry_engagement_id ON knowledge_base_entry(engagement_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_entry_entity_action ON audit_log_entry(entity_name, action_type);
